import Head from "next/head"
// import Test from "@/components/Test"
import { useState } from "react"

export default function Home() {
  const [text, setText] = useState("")
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <textarea name="cosa" value={text} onChange={e => setText(e.target.value)}></textarea>
        {/* <Test markdown={text} /> */}
      </main>
    </>
  )
}
